#!/usr/bin/python
# read an ascii ppm generated by gimp
#
import sys
import png

if len(sys.argv) < 2:
    print "usage: " + sys.argv[0] + " file.mcm\n\n"
    sys.exit(1)

fn = sys.argv[1]
fh = open(fn, "r")

#debug output image
output_w = 192
output_h = 287
pngh = open('font.png', 'wb')
pngw = png.Writer(output_w, output_h, greyscale=True)


#skip MAX7456 coment
version = fh.readline().strip()

font_data = []

for n in range(256):
    for l in range(54):
        line = fh.readline().strip()
        byte = int(line, 2)
        font_data.append(byte)
    for l in range(10):
        # skip 10 dummy bytes
        fh.readline()

# reformat to tinyOSD dataset
font = [[], []]

for data in font_data:
    for i in range(4):
        bitset = (data & 0xC0)>>6
        if (bitset == 0b00):
            # black
            font[0].append(0)
            font[1].append(1)
        elif (bitset == 0b10):
            # white
            font[0].append(1)
            font[1].append(0)
        else:
            # transparent
            font[0].append(0)
            font[1].append(0)
        data = data << 2
    
# debug output png
# font data is one char after the other (12px x 18px)
pngdata = []
for y in range(output_h):
    row = []
    for x in range(output_w):
        # fetch index. we have chars from left to right, top to bot
        char = (y/18)*16+(x/12)
        #print "char %d at %d x %d\n" %(char, x, y)
        idx  = char*(12*18) + (x%12) + ((y%18)*12) 
        if (font[0][idx] == 1):
            color = 0
        elif (font[1][idx] == 1):
            color = 255
        else:
            color = 128
        row.append(color)
    pngdata.append(row)

#print(pngdata)

pngw.write(pngh, pngdata)
pngh.close()


# dump to header
fheader =  open('src/font.h', 'w')

fheader.write("#ifndef __FONT_H__\n")
fheader.write("#define __FONT_H__\n")
fheader.write("\n")

fheader.write("// font data b/w interleaved\n")
fheader.write("static const uint8_t font_data[18][256][3] =  {\n")

# store interleaved data:
# wwww bbbb wwww bbbb wwww bbbb = 12bit white + 12 bit black
count = 0
for row in range(18):
    fheader.write("{")
    for char in range(256):
        index = char*(12*18) + row*12
        
        fheader.write("{")
        for b in range(3):
            byte = 0
            for col in range(2):
                for i in range(4):
                    bit = font[col][index + b*4 + i]
                    byte = (byte << 1) | bit

            fheader.write(hex(byte) + ", ")
        fheader.write("},\n")
        count = count + 3 
    fheader.write("},")
fheader.write("};\n")      

fheader.write("#endif  // __FONT_H__\n")

print ("wrote %d bytes font data" % ( count))


