#!/usr/bin/python
# read an ascii ppm generated by gimp
#
import sys
import png

if len(sys.argv) < 2:
    print "usage: " + sys.argv[0] + " file.png\n\n"
    sys.exit(1)

fn = sys.argv[1]
fh = open(fn, "r")

pngr = png.Reader(fh)
(png_w, png_h, png_data, png_options) = pngr.read()

print png_options

raw_data = list(png_data)

font_black = []
font_white = []

for row in (raw_data):
    for x in range(0, len(row), 4):
        red = row[x]
        if (red == 0):
            # black
            font_black.append(1)
            font_white.append(0)
        elif (red == 255):
            # white
            font_black.append(0)
            font_white.append(1)
        else:
            # transparent
            font_black.append(0)
            font_white.append(0)

print ("got %d bytes of fotn data\n" % (len(font_black)))

#debug output image
max_char = 90
output_w = max_char * 16
output_h = png_h
pngh = open('font.png', 'wb')
pngw = png.Writer(output_w, output_h, greyscale=True)


# debug output png
# font data is one char after the other (12px x 18px)
pngdata = []
for y in range(output_h):
    row = []
    for x in range(max_char):
        for i in range(16):
            idx  = png_w * y + x * 16 + i
            if (font_black[idx] == 1):
                color = 0
            elif (font_white[idx] == 1):
                color = 255
            else:
                color = 128
            row.append(color)
    pngdata.append(row)

#print(pngdata)

pngw.write(pngh, pngdata)

pngh.close()


